apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DJANGO_SETTINGS_MODULE: learning_hub.settings
  DJANGO_DEBUG: "False"
  POSTGRES_HOST: database
  POSTGRES_PORT: "5432"
  POSTGRES_DB: hub_db
  POSTGRES_USER: postgres
  ALLOWED_HOSTS: "*"
